# syntax=docker/dockerfile:1
# Variation 09: Dev image with Xdebug + PHPUnit
# Complexity: MEDIUM
FROM php:8.2-cli-alpine3.18
RUN apk add --no-cache libzip-dev zip unzip linux-headers autoconf g++ make \
    && docker-php-ext-install zip \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del autoconf g++ make
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
WORKDIR /php
COPY ./php/ .
RUN cd example_code/glue && \
    COMPOSER_ALLOW_SUPERUSER=1 composer install
ENV XDEBUG_MODE=coverage
CMD ["bash"]
