# syntax=docker/dockerfile:1
# Variation 03: Development with hot-reload
# Complexity: LOW
# Installs all deps (including devDependencies) for nodemon hot-reload.

FROM node:18

WORKDIR /javascriptv3

COPY ./javascriptv3/package*.json ./

RUN npm install

COPY ./javascriptv3/ .

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npx", "nodemon", "--watch", "example_code", "example_code/s3/s3_basics/s3_basics.js"]
