# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ./dotnetv3/SES/ ./SES/
COPY ./dotnetv3/S3/ ./S3/
COPY ./dotnetv3/IAM/ ./IAM/
RUN echo "=S3=" && find ./S3 -name "*.csproj" && echo "=IAM=" && find ./IAM -name "*.csproj"
