# syntax=docker/dockerfile:1
# Variation 03: Alpine-based minimal
# Complexity: MEDIUM
# Alpine requires musl-dev and gcc for some pip packages.

FROM python:3.11-alpine3.18

RUN apk add --no-cache \
        gcc \
        musl-dev \
        libffi-dev \
        openssl-dev

WORKDIR /python

COPY ./python/example_code/dynamodb/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./python/ .

CMD ["bash"]
