# syntax=docker/dockerfile:1
FROM ghcr.io/graalvm/native-image-community:17 AS native-builder
WORKDIR /build
COPY ./javav2/example_code/cloudwatch/ .
RUN microdnf install -y maven && \
    mvn package -Dmaven.test.skip -Dcheckstyle.skip -q && \
    jar tf target/*.jar | grep '\.class' | head -20
